### ISSUE TITLE
reversed Locking status

### ISSUE THREAD

**Issue by CzechSebastian** [Brandawg93/homebridge-fordpass#127]
Hi,
I have a 2017 Ford Escape and the lock/unlock status is reversed.
When It's locked and I swipe on HomeKit to unlock my car, the switch goes form unlock to lock and return to unlock. 

When I go to Fordpass App and I unlock my car , I can lock my car with homekit, but not all the times.

I see the same issue on reddit post 
https://www.reddit.com/r/homebridge/comments/kehbiy/fordpass_plug_in/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by Brandawg93** [comment]
Hi. I posted a reply there. The top comment is exactly correct. Ford's API is very unreliable and goes down all the time. This causes undefined behavior within Homebridge. You can try either restarting homebridge or deleting the accessory cache within the UI settings to reset the plugin.

**Comment by CzechSebastian** [comment]
I try restarting but same issue.
How can I deleting the accessory cache?
Thanks

**Comment by Brandawg93** [comment]
If you use the [Config UI](https://github.com/oznu/homebridge-config-ui-x#readme), you can go to "Homebridge Settings" > "Manage Cached Accessories" and clear them there.

**Comment by CzechSebastian** [comment]
Same thing after resting all parameters ,
The car is locked, but homekit tells me the opposite.
<img width="414" alt="image" src="https://user-images.githubusercontent.com/46093860/103597320-00e26a80-4ece-11eb-853e-875e7da3ea0b.png">

**Comment by Brandawg93** [comment]
This usually means that FordPass thinks it's unlocked. Their API does not update instantly and sometimes it can take a while for it to update. That's if the API is working at all.

**Comment by CzechSebastian** [comment]
But in the Fordpass App , it still locked.
Everything is ok for remote start, weird...
it will use the same api than the ford app right ?

**Comment by Brandawg93** [comment]
How do you see that the vehicle is locked in the app? My app shows a lock button, but no indication whether the vehicle is locked or not.

**Comment by CzechSebastian** [comment]
ah sorry , you tells right !
does I have the choice to remove this function (lock) ?
and does homekit can show the fuel level ?

**Comment by Brandawg93** [comment]
You cannot currently remove the lock feature. The fuel level is mapped the the battery level of the lock. Try saying, "Hey Siri, what is the fuel level of [device name]?"

**Comment by CzechSebastian** [comment]
It doesn't work anymore...

**Comment by Brandawg93** [comment]
I can confirm it's working on my setup. You can look at the settings of the lock in the Home app to find the battery level.

**Comment by CzechSebastian** [comment]
have you a screenshot where to look ?
I'm struggling now...

**Comment by Brandawg93** [comment]
Press the lock
Press the settings gear
Press accessories
Press the lock
Press the settings gear
Look at battery level

**Comment by CzechSebastian** [comment]
ah ok I have it , but can I have it on my home page ?

**Comment by Brandawg93** [comment]
Not that I know of. You could try asking how to do that on the homebridge community discord. It's in the README.

**Comment by CzechSebastian** [comment]
ok thanks so much
