### ISSUE TITLE
Repeated notifications about unlocked/locked truck

### ISSUE THREAD

**Issue by BatMahn** [Brandawg93/homebridge-fordpass#141]
Hey,

Been using the plugin for a bit. Works great. 

Two things, I get repeated "truck is unlocked" notifications, followed by a "truck is locked" about 10 seconds later throughout the day. This used to happen very occasionally, now it's multiple times a day. 

Also, trying to use Siri to lock the truck doesn't work.  If it's already locked, she just confirms "your truck is locked". If it's unlocked, and I try "hey Siri, lock the truck", she repeatedly just comes back with "your truck is unlocked".

Manually locking via the Home app does work.

**Comment by BatMahn** [comment]
Bad bot.

**Comment by Brandawg93** [comment]
This is an issue with the Fordpass API using cache rather than live data. You could try upping your refresh interval in the plugin settings but note that it may drain your battery a little more than normal.

**Comment by Brandawg93** [comment]
I don't personally use the auto refresh. It would be vehicle specific for what to use. Playing with the settings for your vehicle would be best. 

Glad you enjoy the plugin! 😀
