### ISSUE TITLE
Homebridge Warning

### ISSUE THREAD

**Issue by FranciRoosters** [Brandawg93/homebridge-fordpass#158]
### Describe the bug

When I try to unlock my Ford Fiesta 2017, Homebridge gives me this

You do not have authorization to access Car.
Cannot get information for Car engine.

### Debug Output

N/A

### Steps to reproduce

1. N/A

### Device Type

Raspberry PI

### iOS Version

iOS 15.1

### Bug Persistence

Consistently

**Comment by Brandawg93** [comment]
This should be fixed in v1.5.1. If not, just let me know.

**Comment by FranciRoosters** [comment]
Yeah, I don’t think this fixes it. The locking tile on the Home app keeps spinning and nothing happens. It even shows the car as being unlock when it actually is locked. I’m starting to wonder if my dad is actually Fordpass compatible. Maybe not.

**Comment by Brandawg93** [comment]
Does the Fordpass app work?

**Comment by FranciRoosters** [comment]
It does, but I see no buttons to turn on or lock the car on the app’s main page.
