### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jcleek** [Brandawg93/homebridge-fordpass#159]
### Describe the bug

[13/12/2021, 16:59:40] [FordPass] Status failed with error: 401

I cannot find anywhere that the error codes are listed. That would be awesome, but until then what is 401?

### Debug Output

If debug is required I will run it, but Pi is currently configured to run from startup.

### Steps to reproduce

1. Just look at the log

### Device Type

Raspberry Pi 4 w 4GB

### iOS Version

15.2 but this isn't related to iOS

### Bug Persistence

Consistently

### Last Working Version

Not sure when this started

**Comment by jcleek** [comment]
![Homebridge](https://user-images.githubusercontent.com/16121417/145898887-fe300feb-77d0-4ab1-bc78-f5569a58dbf5.png)

**Comment by Brandawg93** [comment]
401 means that you are not authorized to access that vehicle. Not sure why it would be throwing that assuming your credentials are correct.

**Comment by jcleek** [comment]
I have logged in and back out of the app with the same credentials in the config. I validated the VIN matches in the config. When I restart the server I can lock/unlock but I cannot start the truck. The only error I see is the 401.

So, I followed these steps:
1) Downgraded to 1.4.0 - no help
2) Uninstalled FordPass plugin
3) Rebooted Pi
4) Changed my FordPass password
5) Installed plugin 1.5.0 and configured
6) Rebooted Pi

Lock/unlock works correctly but I cannot start. Siri tells me:

"Sorry, I couldn't find anything like that in your home"

I get that for both "turn on the truck" and "start the truck". "lock/unlock the truck" works as expected. I can start/stop the truck with the FordPass app without issue.

Something is definitely weird. I have done nothing to HomeBridge for several months. Any ideas?

**Comment by Nastras** [comment]
I also did not change anything in config.json or in the FordPass app and have also had this error for 2 days.
![4B0379E7-3C7B-4C13-AF40-0926019AB4D4](https://user-images.githubusercontent.com/27686185/145932625-b34c9462-4a02-4283-8c81-d62ea20a52bf.jpeg)

Since then nothing works anymore.

**Comment by tornenen** [comment]
Same error for me since yesterday.
I can access the car via App and Web with same Credentials.

**Comment by scoobaspeaz** [comment]
I too am having this exact same issue. I disabled the plugin because of its reoccurring notifications via HomeKit.

**Comment by tornenen** [comment]
Changed Password on Web and typed new Password in the Plugin. Nothing changed. Same error.

**Comment by RikBast** [comment]
I have the same error:

[14/12/2021, 14:35:23] [FordPass] Status failed with error: 401

No remote start available with the homebridge plugin.

Using Siri shortcuts works:

https://www.ranger5g.com/forum/threads/fordpass-siri-shortcuts.8200/

**Comment by ewardloi** [comment]
This happened due to the fact that the API for receiving the token changed the token's lifetime by 300 seconds, and in the plugin the token's life is designated as 118 minutes.

to fix this on the current version of the plugin, you need to open the homebridge terminal

`nano node_modules/homebridge-fordpass/dist/index.js`

than go to line with number 7080000
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/18032232/146039905-dd61fb38-9f14-4e62-bff0-b4222f0d5425.png">

and replace 7080000 to 290000
than ctrl+x -> y -> enter
than restart homebridge

**Comment by BatMahn** [comment]
If the lifetime is reduced by 5 minutes, shouldn't it be 6780000?

**Comment by ewardloi** [comment]
in setInterval value set in milliseconds so to get 300 seconds or 5 minutes you should set 1000 * 300 or 1000 * 60 * 5. But to be sure that the token will be new at the next status update request, it is better to hedge and set the update every 290 seconds.
Perhaps in the next version of the plugin it would be good to add that when receiving the 401 status, a request for reauthorization is sent

**Comment by Brandawg93** [comment]
This is fixed in v1.5.1. Thanks for the heads up!

**Comment by Nastras** [comment]
I have exactly the same problem again since two days. What is the situation with you?

**Comment by tornenen** [comment]
Dito

**Comment by ewardloi** [comment]
Its looks like ford blocked clientid used in this client. Because every fordpass api libraries with this clientId stopped working

**Comment by jcleek** [comment]
Sam
![401](https://user-images.githubusercontent.com/16121417/148646163-fa0e8a0b-f1c0-4432-ad51-d391bfe63590.png)
e

**Comment by rulerofthenight** [comment]
same here
