### ISSUE TITLE
[Bug]: error 401

### ISSUE THREAD

**Issue by rulerofthenight** [Brandawg93/homebridge-fordpass#165]
### Describe the bug

Hi
Everything was working great with the plug in, but suddenly I'm getting error 401.
I tried reinstalling the plugin but didn't work
Any ideas?

### Debug Output

Status failed with error: 401

### Steps to reproduce

1. 

### Device Type

Truenas

### iOS Version

15.2

### Bug Persistence

Consistently

**Comment by masav61** [comment]
Same problem!

**Comment by Brandawg93** [comment]
I'm investigating.

**Comment by Brandawg93** [comment]
After some digging, I've found that Ford has removed the option for `password` authentication to their apis. They now only allow `authorization_code` which is much more difficult to implement. They have also secured their app better with MITM attack blockers. Fixing this is doable but may take some time..

**Comment by jcleek** [comment]
Thank you @Brandawg93

**Comment by masav61** [comment]
Solved! Many many thanks @Brandawg93

**Comment by rulerofthenight** [comment]
Hi.
The fix worked for one day. Now the accessory is not reachable again.
Tried to reboot and reinstall the plugin, but no luck

**Comment by jcleek** [comment]
I do not see the issue you see @rulerofthenight. Mine is still working fine. I even restarted Homebridge to see if it would break.
