### ISSUE TITLE
[Bug]: Status failed with error: ENOTFOUND

### ISSUE THREAD

**Issue by tornenen** [Brandawg93/homebridge-fordpass#167]
![2022-01-12 14_24_35-Homebridge 975E und 12 weitere Seiten - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/76594569/149149211-f2aedef6-e203-4b1b-8cec-20bba7ce70d1.jpg)
### Describe the bug

![2022-01-12 14_24_35-Homebridge 975E und 12 weitere Seiten - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/76594569/149148896-85867bcb-62aa-44ac-9ce4-a4a3e4be0883.jpg)

### Debug Output

![2022-01-12 14_24_35-Homebridge 975E und 12 weitere Seiten - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/76594569/149148947-16cd8374-b82d-40c7-901d-cb494287b7fa.jpg)

### Steps to reproduce

1. 

### Device Type

Rapsberry Pi

### iOS Version

15.2

### Bug Persistence

Consistently

**Comment by Brandawg93** [comment]
A few more questions:
1. Just to confirm, this has never worked for you?
2. Are you in the US?
3. `ENOTFOUND` is typically a DNS issue. Are you able to ping `https://sso.ci.ford.com/`?

**Comment by tornenen** [comment]
1.  Just to confirm, this has never worked for you?
     *   It still worked yesterday
  2.  Are you in the US?
     *   No, Germany
  3.  ENOTFOUND is typically a DNS issue. Are you able to ping https://sso.ci.ford.com/?
     *   Ive switched DNS 2 Days ago from 1.1.1.1 to 9.9.9.9, but i can ping this, and my homeassistant can still reach everything at ford.. Using this: itchannel/fordpass-ha: Fordpass integration for Home Assistant (github.com)<https://github.com/itchannel/fordpass-ha>



Von: Brandon McFarlin ***@***.***>
Gesendet: Mittwoch, 12. Januar 2022 14:47
An: Brandawg93/homebridge-fordpass ***@***.***>
Cc: Banko, Kenneth ***@***.***>; Author ***@***.***>
Betreff: Re: [Brandawg93/homebridge-fordpass] [Bug]: Status failed with error: ENOTFOUND (Issue #167)


A few more questions:

  1.  Just to confirm, this has never worked for you?
  2.  Are you in the US?
  3.  ENOTFOUND is typically a DNS issue. Are you able to ping https://sso.ci.ford.com/?

**Comment by Brandawg93** [comment]
If it worked yesterday, I'm not sure what could have changed on the plugin side to affect the functionality. There may be different urls for different regions, but it sounds like yours was already working.

**Comment by rulerofthenight** [comment]
Even mine was working yesterday, after the update that fixed 401 error, but today it won't work. As soon as I come back home I'll check if I have this error or the 401 error again.
P.s. I'm in Europe (Italy)
