### ISSUE TITLE
[Bug]: Unable to authorize

### ISSUE THREAD

**Issue by JeffGoldner** [Brandawg93/homebridge-fordpass#188]
### Describe the bug

I haven't used the plugin for a long time and had it disabled. Today I updated to the latest build and re-enabled, but it throws an error on Authentication when the plug-in (and homebridge) starts. I checked the login credentials, set the region to US, made sure I could log in to the owner.ford.com website with the same creds, and verified that I was still logged in via the FordPass app. My car shows up in both places.

Not sure what to do here. Might try deleting the plugin and reinstalling.

### Debug Output

6/23/2022, 9:05:43 AM] [FordPass] Auth failed with error: ERR_BAD_REQUEST

### Steps to reproduce

1. Enable FordPass
2. Verify settings
3. Restart Homebridge

### Device Type

Official Ubuntu VM/Docker on HyperV (Win10)

### iOS Version

15.5

### Bug Persistence

Consistently

**Comment by Brandawg93** [comment]
Try clearing your accessory cache in Homebridge. The authentication method has recently changed.

**Comment by JeffGoldner** [comment]
> Try clearing your accessory cache in Homebridge. The authentication method has recently changed.

I did nothing but it started working the next day all on its own.

**Comment by BatMahn** [comment]
I'm just now getting the same error. No recent changes, things have been working steady-eddy for months.

Tried clearing accessories, no dice.

Password hasn't changed, I can login via the App with no issues.

Any other suggestions?

**Comment by Brandawg93** [comment]
Make sure the plugin is up-to-date. Ford recently changed some things in their api.

**Comment by BatMahn** [comment]
First thing I tried, also tried rolling back to 1.6x, that gives a 400 error vs the ERR_BAD_REQUEST on 1.7x

**Comment by BatMahn** [comment]
(I am outside of the US too - Canada), I set the region on the advanced settings via Homebridge UI, but after restarting Homebridge, it seems to be stuck on US.. should I change it in the config file manually maybe?

**Comment by BatMahn** [comment]
Maybe something related to what's described here? (ford messing around again)

https://github.com/itchannel/fordpass-ha/issues/187

**Comment by Brandawg93** [comment]
Ford broke their API again...Looks like you can no longer authorize with a username and password.

**Comment by Brandawg93** [comment]
This should be fixed in v1.7.1. Feel free to reopen if you still have issues.

**Comment by BatMahn** [comment]
Hi, just updated, get this error and it crashes home bridge entirely:

UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "AxiosError: Request failed with status code 401".

**Comment by Brandawg93** [comment]
Did you try clearing the cache?

**Comment by BatMahn** [comment]
No, one moment.

**Comment by Brandawg93** [comment]
Try v1.7.2-test.0 and see if that gives you any extra info.

**Comment by BatMahn** [comment]
See attached,
[error.txt](https://github.com/Brandawg93/homebridge-fordpass/files/9013779/error.txt)

**Comment by Brandawg93** [comment]
Ah. It seems to not like your region. Which region have you chosen?

**Comment by BatMahn** [comment]
Ah, that might have been it. I was dinking around with the region earlier. 

Setting back to US seems to get rid of the error.
