### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by LeFumiste** [Brandawg93/homebridge-fordpass#194]
### Describe the bug

2 days ago, impossible to connect with auth failure.

### Debug Output

Auth: ERR_BAD_REQUEST 

### Steps to reproduce

1. 

### Device Type

Raspberry Pi

### iOS Version

15.6

### Bug Persistence

Consistently

### Last Working Version

The same version as today

**Comment by Brandawg93** [comment]
Are you running the latest version of the plugin? This was an issue with the previous version as Ford broke their auth API.

**Comment by LeFumiste** [comment]
Yes, i’m running the latest version of the plugin (1.7.1).
Now: vehicles failed with error: ERR_BAD_RESPONSE 

All of my configuration is the same et nothing changes in the set up. 
But impossible to connect !!!

**Comment by aporzio1** [comment]
I am seeing the same thing on mine

`[7/25/2022, 6:57:12 PM] [FordPass] Vehicles failed with error: ERR_BAD_RESPONSE`

**Comment by tornenen** [comment]
Same here. Dont know since when exactly. 
Just seen my Lock is gone in Homekit. 
[25/07/2022, 20:27:15] [FordPass] Vehicles failed with error: ERR_BAD_RESPONSE

Cleared Cache and restarted HB.

**Comment by fallingrock** [comment]
Seeing the same thing here ... happy to provide additional diagnostics if it would be helpful.

**Comment by Brandawg93** [comment]
v1.8.0 has been published that should hopefully fix this issue. Let me know if not!

**Comment by tornenen** [comment]
Fixed it for me.

**Comment by LeFumiste** [comment]
Fixed it for me.
Thanks a lot …

**Comment by jcleek** [comment]
I still have this issue. Every 60 seconds I get:

[19/08/2022, 16:32:31] [FordPass] Status failed with error: ERR_BAD_REQUEST
[19/08/2022, 16:33:31] [FordPass] Status failed with error: ERR_BAD_REQUEST
[19/08/2022, 16:34:31] [FordPass] Status failed with error: ERR_BAD_REQUEST

You get the idea. Currently running your test 1.8.1
