### ISSUE TITLE
[PSA]: Ford is restricting the ability for people to use this plugin in the US

### ISSUE THREAD

**Issue by Falc0n2k** [Brandawg93/homebridge-fordpass#206]
### Describe the bug

Not really a bug, but I wanted to make the developer and the community using this HB plugin aware that Ford is starting to restrict the ability for owners to use anything but its own FordPass app. 

I got off the phone with FordPass support earlier tonight after my ability to log in to the app and website was restricted. When I gave them the code at the top of my app, the support person said that the code was a "account lock due to a Terms of Service violation". I explained to her that I use a Homebridge plugin to interface with my car (remote lock/unlock and start/stop) because they failed to provide a HomeKit integration. According to their support this constitutes a ToS violation and they will lock your account from being used.

I had the support person escalate my issue to their next highest support team and they'll get back to me within 3-5 days... meanwhile I have no way to remote start my car and the weather here just turned frigid and I'm scheduled to travel across the state next week for the holiday.

For reference, here's the app after it's locked, with the restriction code at the top of the screen.

![IMG_4553](https://user-images.githubusercontent.com/3246415/202821329-ec53a082-552f-44ee-a312-52ccecc265ea.PNG)

Apologies if this isn't the most appropriate place to post this, but as I said above, I wanted both the developer and the community to be aware of what Ford is starting to do.

FTR, I don't see how this is a ToS violation, since it's using an openly accessible API with proper authentication. Nothing about this is reverse engineering or using the API for something it wasn't intended for. If anything, it's merely re-skinning the FordPass API to allow it to be used in HomeKit - hardly a ToS violation in my opinion.

### Debug Output

n/a

### Steps to reproduce

n/a

### Device Type

iPhone 14 Pro Max

### iOS Version

iOS 16.1.1

### Bug Persistence

Consistently

### Last Working Version

1.8.1

**Comment by Brandawg93** [comment]
#196

**Comment by Falc0n2k** [comment]
Thanks, @Brandawg93. Will look at that issue.

**Comment by rackemdiscovery** [comment]
Same issue here. Rep said against policy and because so many people use it now, it’s bringing there servers down. I mean why do they offer APIs was my question, but she’s to low to have any input. A notification about this would have been great instead of account being locked with no way to use app. Oh well hopefully something gets worked out. 

I’m thinking of just creating a new account that I share access to car. Then use that for HomeBridge. If it gets locked, just create another and so on. Hopefully it takes a while for them to figure out I’m using the plugin.
