### ISSUE TITLE
[Bug]: many requests to usapi.cv.ford.com

### ISSUE THREAD

**Issue by Huxly72** [Brandawg93/homebridge-fordpass#207]
### Describe the bug

I am seeing 3-4 requests to http://usapi.cv.ford.com/ every minute on my network. I am concerned and have seen others report their ford account being suspended for too many calls using this plugin. 

Freshly installed, latest version. Refresh was never enabled. I have 2 ford vehicles. 

Possibly same as this closed issue
https://github.com/Brandawg93/homebridge-fordpass/issues/187

Attached screen cap from my network 
![67465E32-0EF8-4429-86A9-FD9DA332CD59](https://user-images.githubusercontent.com/26439753/203190913-3aa80dc7-9c43-420d-ba75-4aab1a51989c.jpeg)

### Debug Output

N/a

### Steps to reproduce

Install plugin
Setup my fordpass Creds 
Monitor network. 

### Device Type

Ubuntu Linux server in docker container

### iOS Version

16.1

### Bug Persistence

Consistently

**Comment by fallingrock** [comment]
My account got suspended by ford due to the plug-in usage. Had to disable it. ☹️

**Comment by Brandawg93** [comment]
#196

**Comment by fallingrock** [comment]
Just saw that.

**Comment by jjyu420** [comment]
Think I got disabled from this plugin

**Comment by csdillon** [comment]
I have been locked out of my Ford account.  I had to open a case with Ford who stated they would not re-enable my account until they see no api hits on the above url using my ford account.

**Comment by jackharvest** [comment]
@Brandawg93 , I've tweeted at them. Don't know if it helps, but there ya go. https://twitter.com/jackharvest/status/1598448217137745920

I would happily take 100% stale information in Homebridge in order to simply be able to Lock, Unlock, and Start the car. Heck, just starting the car with Siri is all I want. Oil, gas, statistics be damned.

**Comment by Brandawg93** [comment]
At this point, I don't think the stale data option would work either if they are blocking other plugins and widgets too.

**Comment by jamesngob** [comment]
I have been locked out by Ford 2 times becuase of this plug-in... I installed this pluggin in 2019 and have not had any issues until around May 2022... I would love to use this plugin again to turn on/off my F150 with Siri but right now, I have to uninstall it to keep my FordPass account active...
Any changes to keep this plugin workable is highly appreciated
