### ISSUE TITLE
[Bug]: in Fordpass

### ISSUE THREAD

**Issue by NOFXNL** [Brandawg93/homebridge-fordpass#218]
### Describe the bug

imkeep getting an error and i cant't find whats.
the error is : [FordPass] User failed with error: ERR_BAD_REQUEST.

and i know for sure tha the login credentials ar correct

### Debug Output

[FordPass] User failed with error: ERR_BAD_REQUEST

### Steps to reproduce

1. i tryed to change my password.
2. i tryed the refress time and off

### Device Type

rassberry pi 4B

### iOS Version

Homebridge V1.6.1

### Bug Persistence

Consistently

### Last Working Version

1.6.1

**Comment by maximuswallis** [comment]
Hello,

I also have this issue! Exactly the same. I am glad I'm not the only one.

It is so upsetting. Hope we can find a solution soon. :)

I have a ford fiesta 2019, in the UK, using EU server. My account is not banned and the app is working fine still. I am new to Fordpass and have only been using it on the most recent version.

I hope that info can help anyone who might know what's going on here.

Max

**Comment by mcneyens** [comment]
Same here. Everything was working fine and then it seems almost as though ford turned off the API we connected to. I’ve verified my account isn’t locked by going to laptop / webpage to log in. 

Great app!  Thanks for making all the recent changes.

**Comment by shutostrike** [comment]
Same here. Brand new setup pi 4B. 
Homebridge 1.6.1
Homebridge FordPass 1.8.2

**Comment by maximuswallis** [comment]
Does anyone know what's going on with this plugin? It's not been working for a long time now. Is it dead? Has ford locked us out? Or does it just need maintenance?

**Comment by Brandawg93** [comment]
Apologies for the delay! This should be fixed in v1.8.3. Please let me know if this works for you.
