### ISSUE TITLE
Auth failed with statut: undefined 

### ISSUE THREAD

**Issue by LeFumiste** [Brandawg93/homebridge-fordpass#236]
### Describe the bug

Error auth 

### Debug Output

No response

### Steps to reproduce

1. 

### Device Type

Raspberry Pi 

### iOS Version

17.1.2

### Bug Persistence

Consistently

### Last Working Version

Last month

**Comment by LeFumiste** [comment]
![Uploading IMG_2558.jpeg…]()

**Comment by Brandawg93** [comment]
This is being tracked on #196. More info there.
