### ISSUE TITLE
[Bug]: Fordpass not showing vehicle

### ISSUE THREAD

**Issue by capw00** [Brandawg93/homebridge-fordpass#240]
### Describe the bug

My vehicle doesn’t show up in hoobs or HomeKit.

### Debug Output

![Uploading image.jpeg
![IMG_2515](https://github.com/Brandawg93/homebridge-fordpass/assets/6945500/b77e5380-9c2a-47db-8afe-1061a889e292)
…]()

### Steps to reproduce

1. 

### Device Type

Hoobs box 

### iOS Version

17.2

### Bug Persistence

Consistently

**Comment by Brandawg93** [comment]
Follow along at #196
