### ISSUE TITLE
You are not authorized to access

### ISSUE THREAD

**Issue by joetlawson** [Brandawg93/homebridge-fordpass#54]
Getting the error in Homebridge I'm not authorized to access the car. I have it setup in the ford pass app and can access with no issues. 

Node.js Version | v12.18.4
-- | --
v6.14.6
root
/homebridge
/homebridge/config.json
/homebridge/node_modules
Yes
Yes

**Comment by joetlawson** [comment]
I may have got this working by logging out and back in to the Ford pass app. I can see it updating status now and now seeing the unauthorized in the logs. I'm just not near the vehicle to determine it is working for sure.

**Comment by Brandawg93** [comment]
Ok. Let me know if it's working for you now.

**Comment by joetlawson** [comment]
Yeah looks like it is working. Thank you for your help!
